//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFrontEnd.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Accountant,Chauffeur,Other")]
        public string Occupations {
            get {
                return ((string)(this["Occupations"]));
            }
            set {
                this["Occupations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int YoungestDriverAge {
            get {
                return ((int)(this["YoungestDriverAge"]));
            }
            set {
                this["YoungestDriverAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int OldestDriverAge {
            get {
                return ((int)(this["OldestDriverAge"]));
            }
            set {
                this["OldestDriverAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int EndingYoungAge {
            get {
                return ((int)(this["EndingYoungAge"]));
            }
            set {
                this["EndingYoungAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int StartingYoungAge {
            get {
                return ((int)(this["StartingYoungAge"]));
            }
            set {
                this["StartingYoungAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double IncreasePremiumValue {
            get {
                return ((double)(this["IncreasePremiumValue"]));
            }
            set {
                this["IncreasePremiumValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double DecreasePremiumValue {
            get {
                return ((double)(this["DecreasePremiumValue"]));
            }
            set {
                this["DecreasePremiumValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26")]
        public int StartingAdultAge {
            get {
                return ((int)(this["StartingAdultAge"]));
            }
            set {
                this["StartingAdultAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double SmallerPercentageIncrease {
            get {
                return ((double)(this["SmallerPercentageIncrease"]));
            }
            set {
                this["SmallerPercentageIncrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double LargerPercentageIncrease {
            get {
                return ((double)(this["LargerPercentageIncrease"]));
            }
            set {
                this["LargerPercentageIncrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SmallerTimeSpanInYears {
            get {
                return ((int)(this["SmallerTimeSpanInYears"]));
            }
            set {
                this["SmallerTimeSpanInYears"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LargerTimeSpanInYears {
            get {
                return ((int)(this["LargerTimeSpanInYears"]));
            }
            set {
                this["LargerTimeSpanInYears"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double DecreaseAmountBasedOnOccupation {
            get {
                return ((double)(this["DecreaseAmountBasedOnOccupation"]));
            }
            set {
                this["DecreaseAmountBasedOnOccupation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double IncreaseAmountBasedOnOccupation {
            get {
                return ((double)(this["IncreaseAmountBasedOnOccupation"]));
            }
            set {
                this["IncreaseAmountBasedOnOccupation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double StartingPremiumAmount {
            get {
                return ((double)(this["StartingPremiumAmount"]));
            }
            set {
                this["StartingPremiumAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chaufeur")]
        public string OccupationsWherePremiumIsIncreased {
            get {
                return ((string)(this["OccupationsWherePremiumIsIncreased"]));
            }
            set {
                this["OccupationsWherePremiumIsIncreased"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Accountant")]
        public string OccupationsWherePremiumIsDecreased {
            get {
                return ((string)(this["OccupationsWherePremiumIsDecreased"]));
            }
            set {
                this["OccupationsWherePremiumIsDecreased"] = value;
            }
        }
    }
}
